---
title: "Publication bias_c2"
author: "Quan Zhou"
date: "2024-03-21"
output: html_document
---


```{r}
library(metafor)
library(MAd)
library("readxl")
##### all NDDs #####
# ============= Load and subset data: combined family c2 =============

# Read in data
datMeta_all <- read_excel("SCA.xlsx")


# Relevant rows only
datMeta_all <- datMeta_all[!is.na(datMeta_all$Full.Ref),]

datMeta_all <- datMeta_all[datMeta_all$Full.Ref != "",]


```


# Grand
```{r}
# ============= Using aggregate function to combine non-independent effect sizes (by study) =============
# Aggregate non-independent effect sizes within publications (aggregate on 'Full.Ref' variable)
# Set correlation between effect sizes to be r=.5, r=.3 and r=.9 and compare
p <- datMeta_all

datMeta <- p
datMeta_agg0.5 <- agg(id=Full.Ref, es=A, var=c2_SE, cor=0.5, data=datMeta)

# Label new aggregated effect sizes with correct cohort
# Use a separate cohort variable with cohorts for aggregation by study (if one study used >1 cohort, they would be lost if not combined into a single row)
agg_by_study_cohorts <- datMeta[!duplicated(datMeta$Full.Ref),]

# Now label cohorts
datMeta_agg0.5$cohort <- agg_by_study_cohorts$Cohort_for_agg_by_study

# Run MREM models       
REM0.5_nocov <- rma.mv(es, var, random = ~ 1 | id, data=datMeta_agg0.5, slab=paste(id, sep="  /  "), method="REML")

### set up 2x2 array for plotting
par(mfrow=c(1,1))

### draw funnel plot
Grand <- funnel(datMeta_agg0.5$es, datMeta_agg0.5$var, refline=0.5,ylim=c(0, 1),xlim=c(-2.5,2.5),
       col=ifelse(datMeta_agg0.5$es > .5, "#023e8a", "#023e8a"),
       xlab="Grand SCA c2", ylab="", cex=1, cex.axis=2, cex.lab=2)


```
# AK
```{r}

# ============= Using aggregate function to combine non-independent effect sizes (by study) =============
# Aggregate non-independent effect sizes within publications (aggregate on 'Full.Ref' variable)
# Set correlation between effect sizes to be r=.5, r=.3 and r=.9 and compare

datMeta <- filter(datMeta_all, Group == "Acquired Knowledge")
datMeta_agg0.5 <- agg(id=Full.Ref, es=A, var=c2_SE, cor=0.5, data=datMeta)

# Label new aggregated effect sizes with correct cohort
# Use a separate cohort variable with cohorts for aggregation by study (if one study used >1 cohort, they would be lost if not combined into a single row)
agg_by_study_cohorts <- datMeta[!duplicated(datMeta$Full.Ref),]

# Now label cohorts
datMeta_agg0.5$cohort <- agg_by_study_cohorts$Cohort_for_agg_by_study

# Run MREM models       
REM0.5_nocov <- rma.mv(es, var, random = ~ 1 | id, data=datMeta_agg0.5, slab=paste(id, sep="  /  "), method="REML")

### set up 2x2 array for plotting
par(mfrow=c(1,1))

### draw funnel plot
AK <- funnel(datMeta_agg0.5$es, datMeta_agg0.5$var, refline=0.5,ylim=c(0, 1),xlim=c(-2.5,2.5),
       col=ifelse(datMeta_agg0.5$es > .5, "#023e8a", "#023e8a"),
       xlab="AK c2", ylab="", cex=1, cex.axis=2, cex.lab=2)


```

# Gf
```{r}

# ============= Using aggregate function to combine non-independent effect sizes (by study) =============
# Aggregate non-independent effect sizes within publications (aggregate on 'Full.Ref' variable)
# Set correlation between effect sizes to be r=.5, r=.3 and r=.9 and compare

datMeta <- filter(datMeta_all, Group == "Gf")
datMeta_agg0.5 <- agg(id=Full.Ref, es=A, var=c2_SE, cor=0.5, data=datMeta)

# Label new aggregated effect sizes with correct cohort
# Use a separate cohort variable with cohorts for aggregation by study (if one study used >1 cohort, they would be lost if not combined into a single row)
agg_by_study_cohorts <- datMeta[!duplicated(datMeta$Full.Ref),]

# Now label cohorts
datMeta_agg0.5$cohort <- agg_by_study_cohorts$Cohort_for_agg_by_study

# Run MREM models       
REM0.5_nocov <- rma.mv(es, var, random = ~ 1 | id, data=datMeta_agg0.5, slab=paste(id, sep="  /  "), method="REML")

### set up 2x2 array for plotting
par(mfrow=c(1,1))

### draw funnel plot
Gf <- funnel(datMeta_agg0.5$es, datMeta_agg0.5$var, refline=0.5,ylim=c(0, 1),xlim=c(-2.5,2.5),
       col=ifelse(datMeta_agg0.5$es > .5, "#023e8a", "#023e8a"),
       xlab="Gf c2", ylab="", cex=1, cex.axis=2, cex.lab=2)


```

# Gc
```{r}

# ============= Using aggregate function to combine non-independent effect sizes (by study) =============
# Aggregate non-independent effect sizes within publications (aggregate on 'Full.Ref' variable)
# Set correlation between effect sizes to be r=.5, r=.3 and r=.9 and compare

datMeta <- filter(datMeta_all, CHC_Category == "Gc")
datMeta_agg0.5 <- agg(id=Full.Ref, es=A, var=c2_SE, cor=0.5, data=datMeta)

# Label new aggregated effect sizes with correct cohort
# Use a separate cohort variable with cohorts for aggregation by study (if one study used >1 cohort, they would be lost if not combined into a single row)
agg_by_study_cohorts <- datMeta[!duplicated(datMeta$Full.Ref),]

# Now label cohorts
datMeta_agg0.5$cohort <- agg_by_study_cohorts$Cohort_for_agg_by_study

# Run MREM models       
REM0.5_nocov <- rma.mv(es, var, random = ~ 1 | id, data=datMeta_agg0.5, slab=paste(id, sep="  /  "), method="REML")

### set up 2x2 array for plotting
par(mfrow=c(1,1))

### draw funnel plot
Gc <- funnel(datMeta_agg0.5$es, datMeta_agg0.5$var, refline=0.5,ylim=c(0, 1),xlim=c(-2.5,2.5),
       col=ifelse(datMeta_agg0.5$es > .5, "#023e8a", "#023e8a"),
       xlab="Gc c2", ylab="", cex=1, cex.axis=2, cex.lab=2)


```

# Grw
```{r}

# ============= Using aggregate function to combine non-independent effect sizes (by study) =============
# Aggregate non-independent effect sizes within publications (aggregate on 'Full.Ref' variable)
# Set correlation between effect sizes to be r=.5, r=.3 and r=.9 and compare

datMeta <- filter(datMeta_all, CHC_Category == "Grw")
datMeta_agg0.5 <- agg(id=Full.Ref, es=A, var=c2_SE, cor=0.5, data=datMeta)

# Label new aggregated effect sizes with correct cohort
# Use a separate cohort variable with cohorts for aggregation by study (if one study used >1 cohort, they would be lost if not combined into a single row)
agg_by_study_cohorts <- datMeta[!duplicated(datMeta$Full.Ref),]

# Now label cohorts
datMeta_agg0.5$cohort <- agg_by_study_cohorts$Cohort_for_agg_by_study

# Run MREM models       
REM0.5_nocov <- rma.mv(es, var, random = ~ 1 | id, data=datMeta_agg0.5, slab=paste(id, sep="  /  "), method="REML")

### set up 2x2 array for plotting
par(mfrow=c(1,1))

### draw funnel plot
Grw <- funnel(datMeta_agg0.5$es, datMeta_agg0.5$var, refline=0.5,ylim=c(0, 1),xlim=c(-2.5,2.5),
       col=ifelse(datMeta_agg0.5$es > .5, "#023e8a", "#023e8a"),
       xlab="Grw c2", ylab="", cex=1, cex.axis=2, cex.lab=2)


```

# Gq
```{r}

# ============= Using aggregate function to combine non-independent effect sizes (by study) =============
# Aggregate non-independent effect sizes within publications (aggregate on 'Full.Ref' variable)
# Set correlation between effect sizes to be r=.5, r=.3 and r=.9 and compare

datMeta <- filter(datMeta_all, CHC_Category == "Gq")
datMeta_agg0.5 <- agg(id=Full.Ref, es=A, var=c2_SE, cor=0.5, data=datMeta)

# Label new aggregated effect sizes with correct cohort
# Use a separate cohort variable with cohorts for aggregation by study (if one study used >1 cohort, they would be lost if not combined into a single row)
agg_by_study_cohorts <- datMeta[!duplicated(datMeta$Full.Ref),]

# Now label cohorts
datMeta_agg0.5$cohort <- agg_by_study_cohorts$Cohort_for_agg_by_study

# Run MREM models       
REM0.5_nocov <- rma.mv(es, var, random = ~ 1 | id, data=datMeta_agg0.5, slab=paste(id, sep="  /  "), method="REML")

### set up 2x2 array for plotting
par(mfrow=c(1,1))

### draw funnel plot
Gq <- funnel(datMeta_agg0.5$es, datMeta_agg0.5$var, refline=0.5,ylim=c(0, 1),xlim=c(-2.5,2.5),
       col=ifelse(datMeta_agg0.5$es > .5, "#023e8a", "#023e8a"),
       xlab="Gq c2", ylab="", cex=1, cex.axis=2, cex.lab=2)


```

# Gkn
```{r}

# ============= Using aggregate function to combine non-independent effect sizes (by study) =============
# Aggregate non-independent effect sizes within publications (aggregate on 'Full.Ref' variable)
# Set correlation between effect sizes to be r=.5, r=.3 and r=.9 and compare

datMeta <- filter(datMeta_all, CHC_Category == "Gkn")
datMeta_agg0.5 <- agg(id=Full.Ref, es=A, var=c2_SE, cor=0.5, data=datMeta)

# Label new aggregated effect sizes with correct cohort
# Use a separate cohort variable with cohorts for aggregation by study (if one study used >1 cohort, they would be lost if not combined into a single row)
agg_by_study_cohorts <- datMeta[!duplicated(datMeta$Full.Ref),]

# Now label cohorts
datMeta_agg0.5$cohort <- agg_by_study_cohorts$Cohort_for_agg_by_study

# Run MREM models       
REM0.5_nocov <- rma.mv(es, var, random = ~ 1 | id, data=datMeta_agg0.5, slab=paste(id, sep="  /  "), method="REML")

### set up 2x2 array for plotting
par(mfrow=c(1,1))

### draw funnel plot
Gkn <- funnel(datMeta_agg0.5$es, datMeta_agg0.5$var, refline=0.5,ylim=c(0, 1),xlim=c(-2.5,2.5),
       col=ifelse(datMeta_agg0.5$es > .5, "#023e8a", "#023e8a"),
       xlab="Gkn c2", ylab="", cex=1, cex.axis=2, cex.lab=2)


```

# Gsm
```{r}

# ============= Using aggregate function to combine non-independent effect sizes (by study) =============
# Aggregate non-independent effect sizes within publications (aggregate on 'Full.Ref' variable)
# Set correlation between effect sizes to be r=.5, r=.3 and r=.9 and compare

datMeta <- filter(datMeta_all, CHC_Category == "Gsm")
datMeta_agg0.5 <- agg(id=Full.Ref, es=A, var=c2_SE, cor=0.5, data=datMeta)

# Label new aggregated effect sizes with correct cohort
# Use a separate cohort variable with cohorts for aggregation by study (if one study used >1 cohort, they would be lost if not combined into a single row)
agg_by_study_cohorts <- datMeta[!duplicated(datMeta$Full.Ref),]

# Now label cohorts
datMeta_agg0.5$cohort <- agg_by_study_cohorts$Cohort_for_agg_by_study

# Run MREM models       
REM0.5_nocov <- rma.mv(es, var, random = ~ 1 | id, data=datMeta_agg0.5, slab=paste(id, sep="  /  "), method="REML")

### set up 2x2 array for plotting
par(mfrow=c(1,1))

### draw funnel plot
Gsm <- funnel(datMeta_agg0.5$es, datMeta_agg0.5$var, refline=0.5,ylim=c(0, 1),xlim=c(-2.5,2.5),
       col=ifelse(datMeta_agg0.5$es > .5, "#023e8a", "#023e8a"),
       xlab="Gsm c2", ylab="", cex=1, cex.axis=2, cex.lab=2)


```

# Ga
```{r}

# ============= Using aggregate function to combine non-independent effect sizes (by study) =============
# Aggregate non-independent effect sizes within publications (aggregate on 'Full.Ref' variable)
# Set correlation between effect sizes to be r=.5, r=.3 and r=.9 and compare

datMeta <- filter(datMeta_all, CHC_Category == "Ga")
datMeta_agg0.5 <- agg(id=Full.Ref, es=A, var=c2_SE, cor=0.5, data=datMeta)

# Label new aggregated effect sizes with correct cohort
# Use a separate cohort variable with cohorts for aggregation by study (if one study used >1 cohort, they would be lost if not combined into a single row)
agg_by_study_cohorts <- datMeta[!duplicated(datMeta$Full.Ref),]

# Now label cohorts
datMeta_agg0.5$cohort <- agg_by_study_cohorts$Cohort_for_agg_by_study

# Run MREM models       
REM0.5_nocov <- rma.mv(es, var, random = ~ 1 | id, data=datMeta_agg0.5, slab=paste(id, sep="  /  "), method="REML")

### set up 2x2 array for plotting
par(mfrow=c(1,1))

### draw funnel plot
Ga <- funnel(datMeta_agg0.5$es, datMeta_agg0.5$var, refline=0.5,ylim=c(0, 1),xlim=c(-2.5,2.5),
       col=ifelse(datMeta_agg0.5$es > .5, "#023e8a", "#023e8a"),
       xlab="Ga c2", ylab="", cex=1, cex.axis=2, cex.lab=2)


```

# Gv
```{r}

# ============= Using aggregate function to combine non-independent effect sizes (by study) =============
# Aggregate non-independent effect sizes within publications (aggregate on 'Full.Ref' variable)
# Set correlation between effect sizes to be r=.5, r=.3 and r=.9 and compare

datMeta <- filter(datMeta_all, CHC_Category == "Gv")
datMeta_agg0.5 <- agg(id=Full.Ref, es=A, var=c2_SE, cor=0.5, data=datMeta)

# Label new aggregated effect sizes with correct cohort
# Use a separate cohort variable with cohorts for aggregation by study (if one study used >1 cohort, they would be lost if not combined into a single row)
agg_by_study_cohorts <- datMeta[!duplicated(datMeta$Full.Ref),]

# Now label cohorts
datMeta_agg0.5$cohort <- agg_by_study_cohorts$Cohort_for_agg_by_study

# Run MREM models       
REM0.5_nocov <- rma.mv(es, var, random = ~ 1 | id, data=datMeta_agg0.5, slab=paste(id, sep="  /  "), method="REML")

### set up 2x2 array for plotting
par(mfrow=c(1,1))

### draw funnel plot
Gv <- funnel(datMeta_agg0.5$es, datMeta_agg0.5$var, refline=0.5,ylim=c(0, 1),xlim=c(-2.5,2.5),
       col=ifelse(datMeta_agg0.5$es > .5, "#023e8a", "#023e8a"),
       xlab="Gv c2", ylab="", cex=1, cex.axis=2, cex.lab=2)


```

# Gs
```{r}

# ============= Using aggregate function to combine non-independent effect sizes (by study) =============
# Aggregate non-independent effect sizes within publications (aggregate on 'Full.Ref' variable)
# Set correlation between effect sizes to be r=.5, r=.3 and r=.9 and compare

datMeta <- filter(datMeta_all, CHC_Category == "Gs")
datMeta_agg0.5 <- agg(id=Full.Ref, es=A, var=c2_SE, cor=0.5, data=datMeta)

# Label new aggregated effect sizes with correct cohort
# Use a separate cohort variable with cohorts for aggregation by study (if one study used >1 cohort, they would be lost if not combined into a single row)
agg_by_study_cohorts <- datMeta[!duplicated(datMeta$Full.Ref),]

# Now label cohorts
datMeta_agg0.5$cohort <- agg_by_study_cohorts$Cohort_for_agg_by_study

# Run MREM models       
REM0.5_nocov <- rma.mv(es, var, random = ~ 1 | id, data=datMeta_agg0.5, slab=paste(id, sep="  /  "), method="REML")

### set up 2x2 array for plotting
par(mfrow=c(1,1))

### draw funnel plot
funnel(datMeta_agg0.5$es, datMeta_agg0.5$var, refline=0.5,ylim=c(0, 1),xlim=c(-2.5,2.5),
       col=ifelse(datMeta_agg0.5$es > .5, "#023e8a", "#023e8a"),
       xlab="Gs c2", ylab="", cex=1, cex.axis=2, cex.lab=2)


```


# arrange plot
```{r}

library(gridExtra)


# Combine plots
combined_plots <- grid.arrange(Grand, AK, Gf, Gc, Grw, Gq, Gkn, Gsm, Ga, Gv, Gs, nrow=3, ncol=4)


```
